# syntax=docker/dockerfile:1.20

ARG BUILDPLATFORM

# build
FROM --platform=$BUILDPLATFORM node:24.15.0-alpine AS build
WORKDIR /app

COPY package*.json ./
COPY --parents ./packages/*/package*.json ./

RUN npm ci

COPY . ./
RUN npm run build


# deploy
FROM nginx:stable-alpine AS deploy
WORKDIR /usr/share/nginx/html

COPY container/nginx-server.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/packages/app/dist ./

EXPOSE 80
